/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet, Text } from "react-native";

const StatItem = ({ label, value }) => (
  <View style={styles.statItem}>
    <Text style={styles.statLabel}>{label}</Text>
    <Text style={styles.statValue}>{value}</Text>
  </View>
);

const ProfileStats = () => {
  const stats = [
    { label: "On Going Orders", value: "5" },
    { label: "Connectors", value: "10" },
    { label: "Post Count", value: "32" },
  ];

  return (
    <View style={styles.container}>
      {stats.map((stat, index) => (
        <StatItem key={index} label={stat.label} value={stat.value} />
      ))}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 20,
  },
  statItem: {
    alignItems: "center",
  },
  statLabel: {
    color: "#A8A8A8",
    fontSize: 16,
    fontFamily: "poppins",
  },
  statValue: {
    color: "#262626",
    fontSize: 24,
    fontFamily: "poppins-bold",
    marginTop: 4,
  },
});

export default ProfileStats;
