/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet, Text, Image } from "react-native";
import { Colors } from "../../../constants/Colors";

const ProfileInfo = () => {
  return (
    <View style={styles.container}>
      <View style={styles.aboutSection}>
        <Text style={styles.aboutTitle}>About Me</Text>
        <Text style={styles.aboutText}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Est amet in
          elit egestas amet, pulvinar. Diam egestas vitae amet in gravida
          condimentum maecenas morbi gravida...{" "}
          <Text style={styles.readMore}>read more</Text>
        </Text>
      </View>
      <Image
        resizeMode="contain"
        source={{
          uri: "https://cdn.builder.io/api/v1/image/assets/TEMP/7ec7e9971135f528387392cf3767579290d8aa96088e301d6fb7c51aa93dc18e?placeholderIfAbsent=true&apiKey=59e835da8ea04b80ab8ace77cb34d866",
        }}
        style={styles.icon}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  aboutSection: {
    flex: 1,
  },
  aboutTitle: {
    color: "rgba(141, 110, 99, 1)",
    fontFamily: "poppins-semibold",
    marginBottom: 8,
    fontSize: 17,

  },
  aboutText: {
    // color: "#8D6E63",
    fontFamily: "poppins",
    fontSize: 14,
    lineHeight: 22,
  },
  readMore: {
    color: Colors.secondaryColor,
    textDecorationLine: "underline",
  },
  icon: {
    width: 20,
    height: 20,
    marginLeft: 10,
  },
});

export default ProfileInfo;
