/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet, Text } from "react-native";

const AboutMe = () => {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>ABOUT ME</Text>
      <Text style={styles.description}>
        Perera Handlooms is a family-owned business based in Colmbo, Sri Lanka,
        specializing in high-quality handloom textiles. For over 25 years, we
        have been expoting traditional Sri Lankan textiles, including sarongs,
        shawls, and home décor items, using eco-friendly dyes and sustainable
        materials.
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    marginTop: 0,
  },
  title: {
    color: "rgba(141, 110, 99, 1)",
    fontFamily: "poppins-semibold",
    fontSize: 19,
  },
  description: {
    color: "#262626",
    fontFamily: "poppins",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
});

export default AboutMe;
