/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet, Image, Text, ScrollView } from "react-native";
import FormInput from "./FormInput";
import FormSelect from "./FormSelect";
import SubmitButton from "./SubmitButton";

const AddBidDetails = () => {
  const formInputs = [
    { label: "Title", placeholder: "Post Title" },
    { label: "Address", placeholder: "Enter your working/ home address" },
    { label: "Description", placeholder: "Bid Description", multiline: true },
  ];

  const selectInputs = [
    { label: "Category", placeholder: "Select Product Category" },
    { label: "Bid Closing Time", placeholder: "Select Your Bid Closing Time" },
  ];

  return (
    <ScrollView style={styles.container}>
    
      <View style={styles.content}>
        <View style={styles.titleContainer}>
          <Text style={styles.title}>Add Bid Details</Text>
        </View>
        <View style={styles.formContainer}>
          <View style={styles.imageUploadContainer}>
            <Text style={styles.label}>Add Image</Text>
            <View style={styles.imageUploadBox}>
            
            </View>
          </View>
          {formInputs.map((input, index) => (
            <FormInput key={index} {...input} />
          ))}
          {selectInputs.map((select, index) => (
            <FormSelect key={index} {...select} />
          ))}
        </View>
        <SubmitButton title="Add a Post" />
      </View>
      
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  headerImage: {
    width: "100%",
    aspectRatio: 8.62,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  content: {
    padding: 16,
  },
  titleContainer: {
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#EFEFF0",
    paddingBottom: 20,
    marginBottom: 17,
  },
  title: {
    fontSize: 14,
    fontWeight: "500",
    color: "#080422",
    fontFamily: "Poppins, sans-serif",
  },
  formContainer: {
    width: "100%",
    maxWidth: 381,
    alignSelf: "center",
  },
  imageUploadContainer: {
    marginBottom: 9,
  },
  label: {
    color: "#000",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.4,
    fontFamily: "Lato, sans-serif",
    marginBottom: 8,
  },
  imageUploadBox: {
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#AFB1B6",
    backgroundColor: "rgba(211, 113, 69, 0.03)",
    height: 150,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadIcon: {
    width: 24,
    height: 24,
  },
  footerImage: {
    width: "100%",
    aspectRatio: 5.18,
    marginTop: 17,
  },
});

export default AddBidDetails;
