/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Text, TouchableOpacity, StyleSheet, Image } from "react-native";

const FormSelect = ({ label, placeholder }) => {
  return (
    <View style={styles.container}>
      <Text style={styles.label}>{label}</Text>
      <TouchableOpacity style={styles.selectButton}>
        <Text style={styles.placeholder}>{placeholder}</Text>
        <Image
          resizeMode="contain"
          source={{
            uri: "https://cdn.builder.io/api/v1/image/assets/TEMP/94a91a52ceb58a5204e6a56eed4ad34f07d9cac81e89a11ecdf898ce8241fc3c?placeholderIfAbsent=true&apiKey=59e835da8ea04b80ab8ace77cb34d866",
          }}
          style={styles.icon}
        />
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    marginBottom: 9,
  },
  label: {
    color: "#000",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.4,
    fontFamily: "Lato, sans-serif",
    marginBottom: 8,
  },
  selectButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#AFB1B6",
    backgroundColor: "rgba(211, 113, 69, 0.03)",
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  placeholder: {
    fontSize: 12,
    color: "#61646B",
    fontFamily: "Lato, sans-serif",
  },
  icon: {
    width: 15,
    height: 15,
  },
});

export default FormSelect;
