/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { TouchableOpacity, Text, StyleSheet } from "react-native";

const SubmitButton = ({ title }) => {
  return (
    <TouchableOpacity style={styles.button}>
      <Text style={styles.buttonText}>{title}</Text>
    </TouchableOpacity>
  );
};

const styles = StyleSheet.create({
  button: {
    borderRadius: 35,
    backgroundColor: "rgba(170, 106, 28, 1)",
    minHeight: 52,
    width: "100%",
    maxWidth: 361,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 19,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "rgba(161, 136, 127, 1)",
    marginTop: 6,
    alignSelf: "center",
  },
  buttonText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "Lato, sans-serif",
    textAlign: "center",
  },
});

export default SubmitButton;
